spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frew
    username: root
    password: ilyas#@2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
#    root: INFO
#    org.springframework: DEBUG
#    your.package.name: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    sql: debug



